name: Setup Turborepo
description: Setup PNPM, Node.js and the Turborepo remote cache server

inputs:
  node-registry-url:
    description: The Node.js registry URL to use
    required: false

  node-version:
    description: The Node.js version to use
    required: false

  node-version-file:
    description: The file to read the Node.js version from
    required: false

  pnpm-install-args:
    description: Additional arguments to pass to `pnpm install`
    default: --frozen-lockfile

  pnpm-version:
    description: The version of PNPM to use
    required: false

  turbo-s3-endpoint:
    description: S3 endpoint for Turbo cache server
    required: false

  turbo-s3-region:
    description: S3 region for Turbo cache server
    required: false

  turbo-s3-bucket:
    description: S3 bucket name for Turbo cache server
    required: false

  turbo-s3-access-key:
    description: S3 access key for Turbo cache server
    required: false

  turbo-s3-secret-key:
    description: S3 secret key for Turbo cache server
    required: false

  turbo-team:
    description: The Turbo team to use for caching
    required: false

  turbo-token:
    description: The value will be checked by the cache server
    required: false

outputs:
  node-version:
    description: The installed node version
    value: ${{ steps.export.outputs.node-version }}

  pnpm-version:
    description: The installed PNPM version
    value: ${{ steps.export.outputs.pnpm-version }}

  turbo-version:
    description: The installed Turbo version
    value: ${{ steps.export.outputs.turbo-version }}

runs:
  using: composite
  steps:
    - name: Setup variables
      id: setup-vars
      run: |
        # Setup variables
        if [ "${{ inputs.node-version-file }}" != "" ]; then
          echo "node-version-file=${{ inputs.node-version-file }}" >> $GITHUB_OUTPUT
        elif [ -f ".node-version" ]; then
          echo "node-version-file=.node-version" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Setup PNPM
      uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ steps.setup-vars.outputs.node-version-file }}
        cache: pnpm
        registry-url: ${{ inputs.node-registry-url }}

    - name: Export Turbo environment variables
      if: ${{ inputs.turbo-s3-bucket != '' }}
      run: |
        # Export Turbo environment variables
        echo "TURBO_API=http://127.0.0.1:8585" >> $GITHUB_ENV
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "TURBO_SCM_BASE=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
        fi
        if [ "${{ inputs.turbo-team }}" == "" ]; then
          echo "TURBO_TEAM=${{ github.repository }}" >> $GITHUB_ENV
        else
          echo "TURBO_TEAM=${{ inputs.turbo-team }}" >> $GITHUB_ENV
        fi
        echo "TURBO_TELEMETRY_DISABLED=1" >> $GITHUB_ENV
        echo "TURBO_TOKEN=${{ inputs.turbo-token }}" >> $GITHUB_ENV
      shell: bash

    - name: Setup Turbo cache server
      if: ${{ inputs.turbo-s3-bucket != '' }}
      uses: brunojppb/turbo-cache-server@c906d49828dc0a8e28b2099ac40b69c726c4bdf4 # 4.0.1
      env:
        PORT: "8585"
        S3_ENDPOINT: ${{ inputs.turbo-s3-endpoint }}
        S3_REGION: ${{ inputs.turbo-s3-region }}
        S3_BUCKET_NAME: ${{ inputs.turbo-s3-bucket }}
        S3_ACCESS_KEY: ${{ inputs.turbo-s3-access-key }}
        S3_SECRET_KEY: ${{ inputs.turbo-s3-secret-key }}

    - name: Install dependencies
      run: pnpm install ${{ inputs.pnpm-install-args }}
      shell: bash

    - name: Export outputs
      id: export
      run: |
        # Get the installed Node.js, PNPM and Turbo versions
        node_version=${{ steps.setup-node.outputs.node-version }}
        echo "Installed Node.js version: $node_version"
        echo "node-version=$node_version" >> $GITHUB_OUTPUT
        pnpm_version=$(pnpm --version)
        echo "Installed PNPM version: $pnpm_version"
        echo "pnpm-version=$pnpm_version" >> $GITHUB_OUTPUT
        turbo_version=$(pnpm ls --depth 0 --json turbo | jq -r '.[0].dependencies.turbo.version,.[0].devDependencies.turbo.version | select(. != null)')
        echo "Installed Turbo version: $turbo_version"
        echo "turbo-version=$turbo_version" >> $GITHUB_OUTPUT
      shell: bash
