version: 2

updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /build-expo-app
      - /deploy-expo-app
      - /setup-java
      - /setup-turborepo
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
