name: Build Expo App
description: Build an Expo app using EAS

inputs:
  local:
    description: Run build locally?
    default: "false"

  profile:
    description: Name of the build profile
    required: false

  submit:
    description: Auto submit to the store? (production profile only)
    default: "false"

  working-directory:
    description: Working directory for the build command
    required: false

outputs:
  app-build-version:
    description: App build version
    value: ${{ steps.build.outputs.result && fromJson(steps.build.outputs.result)[0].appBuildVersion }}

  app-version:
    description: App version
    value: ${{ steps.build.outputs.result && fromJson(steps.build.outputs.result)[0].appVersion }}

  artifact-digest:
    description: Build artifact digest
    value: ${{ steps.upload.outputs.artifact-digest }}

  artifact-id:
    description: Build artifact ID
    value: ${{ steps.upload.outputs.artifact-id }}

  artifact-url:
    description: URL to the build artifact
    value: ${{ steps.upload.outputs.artifact-url }}

  profile:
    description: Name of the build profile
    value: ${{ steps.build.outputs.result && fromJson(steps.build.outputs.result)[0].buildProfile }}

runs:
  using: composite
  steps:
    - name: Setup variables
      id: setup-vars
      run: |
        # Setup variables
        working_directory="${{ inputs.working-directory || env.EAS_WORKING_DIRECTORY || github.workspace }}"
        echo "artifact-name=$(basename $working_directory)" >> $GITHUB_OUTPUT
        echo "working-directory=$working_directory" >> $GITHUB_OUTPUT
      shell: bash

    - name: Build app
      uses: actions/github-script@v8
      id: build
      env:
        ARTIFACT_NAME: ${{ steps.setup-vars.outputs.artifact-name }}
        WORKING_DIRECTORY: ${{ steps.setup-vars.outputs.working-directory }}
      with:
        script: |
          const args = ['build', '--json', '--non-interactive'];
          const profile = core.getInput('profile');
          if (profile !== '') {
            args.push(`--profile=${ profile }`);
          }
          const submit = core.getInput('submit');
          if (profile === 'production' && submit === 'true') {
            args.push('--auto-submit');
          }
          const local = core.getInput('local');
          if (local === 'true') {
            args.push('--local');
            if (profile === 'production') {
              args.push(`--output=build/${ process.env.ARTIFACT_NAME }.aab`);
            } else {
              args.push(`--output=build/${ process.env.ARTIFACT_NAME }.apk`);
            }
          } else {
            args.push('--wait');
          }
          const { stdout } = await exec.getExecOutput('eas', args, { cwd: process.env.WORKING_DIRECTORY });
          return JSON.parse(stdout);

    - name: Download app
      if: ${{ steps.build.outputs.result && inputs.local != 'true' }}
      env:
        ARTIFACT_NAME: ${{ steps.setup-vars.outputs.artifact-name }}
        WORKING_DIRECTORY: ${{ steps.setup-vars.outputs.working-directory }}
      run: |
        # Create build directory and download the artifact
        mkdir -p ${WORKING_DIRECTORY}/build
        if [ "${{ fromJson(steps.build.outputs.result)[0].buildProfile }}" = "production" ]; then
          curl -fLs ${{ fromJson(steps.build.outputs.result)[0].artifacts.buildUrl }} --output ${WORKING_DIRECTORY}/build/${ARTIFACT_NAME}.aab
        else
          curl -fLs ${{ fromJson(steps.build.outputs.result)[0].artifacts.buildUrl }} --output ${WORKING_DIRECTORY}/build/${ARTIFACT_NAME}.apk
        fi
      shell: bash

    - name: Upload build artifact
      uses: actions/upload-artifact@v7
      id: upload
      with:
        name: ${{ steps.setup-vars.outputs.artifact-name }}.zip
        path: ${{ steps.setup-vars.outputs.working-directory }}/build
        retention-days: 7
