name: Setup EAS
description: Setup EAS

inputs:
  eas-project-id:
    description: EAS project ID
    required: true

  eas-version:
    description: EAS version to use
    default: latest

  eas-version-file:
    description: The file to read the EAS version from
    required: false

  environment:
    description: Build environment
    required: false

  expo-token:
    description: Token of your Expo account
    required: true

  platform:
    description: Platform to build for (all/android/ios)
    required: false

  working-directory:
    description: Working directory for the build command
    required: false

outputs:
  eas-version:
    description: The installed EAS version
    value: ${{ steps.export.outputs.eas-version }}

runs:
  using: composite
  steps:
    - name: Setup variables
      id: setup-vars
      run: |
        # Setup variables
        working_directory="${{ inputs.working-directory || env.EAS_WORKING_DIRECTORY || github.workspace }}"
        if [ "${{ inputs.eas-version-file }}" != "" ]; then
          echo "eas-version=$(cat '${{ inputs.eas-version-file }}')" >> $GITHUB_OUTPUT
        elif [ -f "$working_directory/.eas-version" ]; then
          echo "eas-version=$(cat "$working_directory/.eas-version")" >> $GITHUB_OUTPUT
        else
          echo "eas-version=${{ inputs.eas-version }}" >> $GITHUB_OUTPUT
        fi
        echo "working-directory=$working_directory" >> $GITHUB_OUTPUT
      shell: bash

    - name: Setup EAS
      uses: expo/expo-github-action@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e # v8.2.1
      with:
        eas-version: ${{ steps.setup-vars.outputs.eas-version }}
        eas-cache: false
        packager: pnpm
        token: ${{ inputs.expo-token }}

    - name: Configure EAS project
      if: ${{ inputs.eas-project-id != '' }}
      run: |
        # Configure EAS project
        eas init --id=${{ inputs.eas-project-id }} --force --non-interactive
      shell: bash
      working-directory: ${{ steps.setup-vars.outputs.working-directory }}

    - name: Configure EAS project to support EAS build
      if: ${{ inputs.platform != '' }}
      run: |
        # Configure EAS project to support EAS build
        eas build:configure --platform=${{ inputs.platform }}
      shell: bash
      working-directory: ${{ steps.setup-vars.outputs.working-directory }}

    - name: Configure EAS project to support EAS update
      if: ${{ inputs.platform != '' }}
      run: |
        # Configure EAS project to support EAS update
        if [ "${{ inputs.environment }}" != "" ]; then
          eas update:configure --platform=${{ inputs.platform }} --environment=${{ inputs.environment }} --non-interactive
        else
          eas update:configure --platform=${{ inputs.platform }} --non-interactive
        fi
      shell: bash
      working-directory: ${{ steps.setup-vars.outputs.working-directory }}

    - name: Pull environment variables
      if: ${{ inputs.environment != '' }}
      run: |
        # Pull environment variables
        eas env:pull --environment=${{ inputs.environment }} --non-interactive
      shell: bash
      working-directory: ${{ steps.setup-vars.outputs.working-directory }}

    - name: Export EAS environment variables
      run: |
        # Export EAS environment variables
        echo "EAS_PLATFORM=${{ inputs.platform }}" >> $GITHUB_ENV
        echo "EAS_WORKING_DIRECTORY=$(realpath ${{ steps.setup-vars.outputs.working-directory }})" >> $GITHUB_ENV
      shell: bash

    - name: Export outputs
      id: export
      run: |
        # Get the installed EAS CLI version
        eas_version=$(eas --version 2>&1 | grep 'eas-cli/' | cut -d' ' -f1 | cut -d'/' -f2)
        echo "Installed EAS CLI version: $eas_version"
        echo "eas-version=$eas_version" >> $GITHUB_OUTPUT
      shell: bash
